"""add_unique_index_to_users

Revision ID: ваш_автосгенерированный_id
Revises: предыдущая_миграция
Create Date: 2024-01-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ваш_автосгенерированный_id'
down_revision = 'предыдущая_миграция'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_user_id_unique', 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_user_id_unique', table_name='users')
    # ### end Alembic commands ###