"""Initial migration

Revision ID: c640465a3c1e
Revises: 
Create Date: 2025-09-13 01:15:24.760686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c640465a3c1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bachelor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lvl_education', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=False),
    sa.Column('file_work', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bachelor'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('count_proposed_works', sa.Integer(), nullable=False),
    sa.Column('count_works_ordered', sa.Integer(), nullable=False),
    sa.Column('list_order', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('bachelor')
    # ### end Alembic commands ###